# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  pipelines:
    - pipeline: buildContosoAir # identifier for the
      source: mpieler.ContosoAir
      trigger:
        branches:
         include:
         - master
pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'specific'
    project: '47fc85ca-9638-4c03-9dc8-5034fd7cdf74'
    pipeline: '5'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Pass - Sponsorship(66733ed4-071d-45a6-9f97-d0a5d1b7d75d)'
    appType: 'webApp'
    WebAppName: '$(web_prefix) $(web_site) $(web_environment)'
    packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'
    specificBuildWithTriggering: true
    buildVersionToDownload: 'latest'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Pass - Sponsorship(66733ed4-071d-45a6-9f97-d0a5d1b7d75d)'
    appType: 'webApp'
    WebAppName: 'pul-ai-gragsdale'
    packageForLinux: '$(System.DefaultArtifactsDirectory)/**/*.zip'